// <auto-generated />
using Finances.Dal.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finances.Dal.Migrations
{
    [DbContext(typeof(FinancesContext))]
    [Migration("20241217164354_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finances.Dal.Entities.Finances", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Period")
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<double>("AmountOfMoney")
                        .HasColumnType("double precision")
                        .HasColumnName("amount_of_money");

                    b.Property<double>("AverageSurplus")
                        .HasColumnType("double precision")
                        .HasColumnName("average_surplus");

                    b.Property<double>("AverageWasted")
                        .HasColumnType("double precision")
                        .HasColumnName("average_wasted");

                    b.Property<double>("Debt")
                        .HasColumnType("double precision")
                        .HasColumnName("debt");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<double>("Income")
                        .HasColumnType("double precision")
                        .HasColumnName("income");

                    b.Property<double>("MountsToGoal")
                        .HasColumnType("double precision")
                        .HasColumnName("mounts_to_goal");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("SavingGoal")
                        .HasColumnType("double precision")
                        .HasColumnName("saving_goal");

                    b.Property<double>("TotalWastedSum")
                        .HasColumnType("double precision")
                        .HasColumnName("total_wasted_sum");

                    b.HasKey("UserId", "Period")
                        .HasName("pk_finances");

                    b.ToTable("finances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
